spring:
  application:
    name: backend

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_exchange

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  expiration: 3600000